nama : RDP_COFFIN

pada : alur kerja_dispatch

pekerjaan :
  membangun :

    berjalan-on : windows-terbaru
    menit-waktu habis : 9999

    langkah-langkah :
    - nama : Download Ngrok & NSSM
      lari : |
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/master/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/c9ffin/RDP_COFFIN/main/Files/nssm.exe -OutFile nssm.exe
    - nama : Salin NSSM & Ngrok ke Direktori Windows.
      lari : |
        salin nssm.exe C:\Windows\System32
        salin ngrok.exe C:\Windows\System32
    - nama : Hubungkan akun NGROK Anda
      jalankan : .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env :
        NGROK_AUTH_TOKEN : ${{ rahasia.NGROK_AUTH_TOKEN }}
    - nama : Download File Penting.
      lari : |
        Invoke-WebRequest https://raw.githubusercontent.com/c9ffin/RDP_COFFIN/main/Files/NGROK-US.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/c9ffin/RDP_COFFIN/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/c9ffin/RDP_COFFIN/main/Files/loop.bat -OutFile loop.bat
    - name : Buat file YML untuk NGROK.
      jalankan : mulai NGROK-US.bat
    - nama : Aktifkan Akses RDP.
      lari : |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-nama "fDenyTSConnections" -Nilai 0
        Aktifkan-NetFirewallRule -DisplayGroup "Desktop Jarak Jauh"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -nama "UserAuthentication" -Nilai 1
    - nama : Buat Terowongan
      jalankan : sc start ngrok
    - nama : Hubungkan ke Ram RDP 2core-7GB Anda.
      jalankan : cmd /c NGROK-CHECK.bat
    - nama : Semua Selesai! Anda dapat menutup Tab sekarang! Waktu VM maksimum: 6 jam.
      jalankan : cmd /c loop.bat
